apiVersion: v1
kind: Service
metadata:
  name: oidc
  labels:
    app: oidc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: oidc
  ports:
    - protocol: TCP
      port: 8080
