// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

// Defines values for TokenParamsGrantType.
const (
	AuthorizationCode                     TokenParamsGrantType = "authorization_code"
	ClientCredentials                     TokenParamsGrantType = "client_credentials"
	Password                              TokenParamsGrantType = "password"
	RefreshToken                          TokenParamsGrantType = "refresh_token"
	UrnIetfParamsOauthGrantTypeDeviceCode TokenParamsGrantType = "urn:ietf:params:oauth:grant-type:device_code"
)

// OpenIDConfigurationResponseSchema defines model for OpenIDConfigurationResponseSchema.
type OpenIDConfigurationResponseSchema struct {
	// AuthorizationEndpoint http://localhost:1234/op/authorize
	AuthorizationEndpoint string `json:"authorization_endpoint"`

	// Issuer http://localhost:1234/op
	Issuer string `json:"issuer"`

	// RevocationEndpoint http://localhost:1234/op/revoke
	RevocationEndpoint string `json:"revocation_endpoint"`

	// TokenEndpoint http://localhost:1234/op/token
	TokenEndpoint string `json:"token_endpoint"`

	// UserinfoEndpoint http://localhost:1234/op/userinfo
	UserinfoEndpoint string `json:"userinfo_endpoint"`
}

// SignInRequestSchema defines model for SignInRequestSchema.
type SignInRequestSchema struct {
	// Id id
	Id string `json:"id"`

	// Password password
	Password string `json:"password"`
}

// SignUpRequestSchema defines model for SignUpRequestSchema.
type SignUpRequestSchema struct {
	// Id id
	Id string `json:"id"`

	// Password password
	Password string `json:"password"`
}

// TokenResponseSchema https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#TokenResponse
type TokenResponseSchema struct {
	// AccessToken access_token
	AccessToken *string `json:"access_token,omitempty"`

	// ExpiresIn expires_in
	ExpiresIn *int `json:"expires_in,omitempty"`

	// IdToken id_token
	IdToken *string `json:"id_token,omitempty"`

	// RefreshToken refresh_token
	RefreshToken *string `json:"refresh_token,omitempty"`

	// TokenType token_type
	TokenType *string `json:"token_type,omitempty"`
}

// TokenParams defines parameters for Token.
type TokenParams struct {
	// GrantType grant_type
	GrantType *TokenParamsGrantType `form:"grant_type,omitempty" json:"grant_type,omitempty"`

	// Code code
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// RedirectUri http://localhost:1234/rp/auth/callback
	RedirectUri *string `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
}

// TokenParamsGrantType defines parameters for Token.
type TokenParamsGrantType string

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequestSchema

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequestSchema
