services:
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7.0.11-alpine
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  oidc:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${OIDC_PORT}:1234
    environment:
      ENV: ${ENV}
      REDIS_URL: redis:6379
      # DEBUG_MODE: ${DEBUG_MODE}
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - redis
