openapi: 3.0.3
info:
  title: Open ID Connect App
  description: |-
    This is the OIDC OpenID API documentation.
  termsOfService: https://localhost:1234
  contact:
    email: morning.night.dream@example.com
  license:
    name: MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:1234
tags:
  - name: IdP
    description: Identity Provider
  - name: OP
    description: OpenID Provider
  - name: RP
    description: Relying Party
paths:
  /idp/signup:
    post:
      tags:
        - IdP
      summary: Sign Up
      description: Sign Up
      operationId: idpSignUp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdPSignUpRequestSchema'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /id/signin:
    post:
      tags:
        - IdP
      summary: Sign In
      description: Sign In
      operationId: idpSignIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdPSignInRequestSchema'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /op/.well-known/openid-configuration:
    get:
      tags:
        - OP
      summary: OpenID Provider Configuration
      description: OpenID Provider Configuration
      operationId: opOpenIDConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OPOpenIDConfigurationResponseSchema'
        '500':
          description: Internal Server Error
  /op/authorize:
    get:
      tags:
        - OP
      summary: Authentication Request
      description: Authentication Request
      operationId: opAuthorize
      parameters:
        - name: response_type
          in: query
          description: response_type
          schema:
            type: string
            enum:
              - code
              - id_token
              - token
              - code id_token
              - code token
              - id_token token
              - code id_token token
        - name: scope
          in: query
          description: scope
          schema:
            type: string
            enum:
              - openid
              - profile
              - email
              - address
              - phone
              - offline_access
        - name: client_id
          in: query
          description: client_id
          schema:
            type: string
            format: uri
            example: client_id
        - name: state
          in: query
          description: state
          schema:
            type: string
            example: state
        - name: redirect_uri
          in: query
          description: http://localhost:1234/rp/auth/callback
          schema:
            type: string
            format: uri
            example: http://localhost:1234/rp/auth/callback
      responses:
        '302':
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:1234/rp/auth/callback
        '500':
          description: Internal Server Error
  /op/token:
    post:
      tags:
        - OP
      summary: Token Request
      description: https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#TokenRequest
      operationId: opToken
      parameters:
        - name: grant_type
          in: query
          description: grant_type
          schema:
            type: string
            enum:
              - authorization_code
              - refresh_token
              - client_credentials
              - password
              - urn:ietf:params:oauth:grant-type:device_code
        - name: code
          in: query
          description: code
          schema:
            type: string
        - name: redirect_uri
          in: query
          description: http://localhost:1234/rp/auth/callback
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OPTokenResponseSchema'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: error
                    example: invalid_request
        '500':
          description: Internal Server Error
  /rp/login:
    get:
      tags:
        - RP
      summary: RP Login
      description: RP Login
      operationId: rpLogin
      responses:
        '302':
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:1234/op/authorize
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: api-key
      in: header
  schemas:
    IdPSignUpRequestSchema:
      type: object
      properties:
        id:
          type: string
          description: id
          example: id
        password:
          type: string
          description: password
          example: password
      required:
        - id
        - password
    IdPSignInRequestSchema:
      type: object
      properties:
        id:
          type: string
          description: id
          example: id
        password:
          type: string
          description: password
          example: password
      required:
        - id
        - password
    OPOpenIDConfigurationResponseSchema:
      type: object
      properties:
        issuer:
          type: string
          description: http://localhost:1234/op
          format: uri
          example: http://localhost:1234/op
        authorization_endpoint:
          type: string
          description: http://localhost:1234/op/authorize
          format: uri
          example: http://localhost:1234/op/authorize
        token_endpoint:
          type: string
          description: http://localhost:1234/op/token
          format: uri
          example: http://localhost:1234/op/token
        userinfo_endpoint:
          type: string
          description: http://localhost:1234/op/userinfo
          format: uri
          example: http://localhost:1234/op/userinfo
        revocation_endpoint:
          type: string
          description: http://localhost:1234/op/revoke
          format: uri
          example: http://localhost:1234/op/revoke
      required:
        - issuer
        - authorization_endpoint
        - token_endpoint
        - userinfo_endpoint
        - revocation_endpoint
    AuthRequestSchema:
      type: object
      description: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
      properties:
        scopes:
          type: array
          description: https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
          items:
            type: string
            enum:
              - openid
              - profile
              - email
              - address
              - phone
              - offline_access
        response_type:
          type: string
          enum:
            - code
            - id_token
            - token
            - code id_token
            - code token
            - id_token token
            - code id_token token
        client_id:
          type: string
          description: client_id
          format: uri
          example: client_id
        redirect_uri:
          type: string
          description: http://localhost:1234/rp/auth/callback
          format: uri
          example: http://localhost:1234/rp/auth/callback
        state:
          type: string
          description: state
          example: state
        nonce:
          type: string
          description: nonce
          example: nonce
        response_mode:
          type: string
          enum:
            - query
            - fragment
        display:
          type: string
          enum:
            - page
            - popup
            - touch
            - wap
        prompt:
          type: string
          enum:
            - none
            - login
            - consent
            - select_account
        max_age:
          type: integer
          format: int64
          minimum: 0
        ui_locales:
          type: string
          description: ui_locales
          example: ui_locales
        id_token_hint:
          type: string
          description: id_token_hint
          example: id_token_hint
        login_hint:
          type: string
          description: login_hint
          example: login_hint
        acr_values:
          type: array
          description: acr_values
          items:
            type: string
        code_challenge:
          type: string
          description: code_challenge
          example: code_challenge
        code_challenge_method:
          type: string
          enum:
            - plain
            - S256
      required:
        - scopes
        - response_type
        - client_id
        - redirect_uri
        - state
        - nonce
        - response_mode
        - display
        - prompt
        - max_age
        - ui_locales
        - id_token_hint
        - login_hint
        - acr_values
        - code_challenge
        - code_challenge_method
    OPTokenResponseSchema:
      type: object
      description: https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#TokenResponse
      properties:
        access_token:
          type: string
          description: access_token
          example: access_token
        token_type:
          type: string
          description: token_type
          example: token_type
        refresh_token:
          type: string
          description: refresh_token
          example: refresh_token
        expires_in:
          type: integer
          description: expires_in
          example: 3600
        id_token:
          type: string
          description: id_token
          example: id_token
    IDTokenSchema:
      type: object
      description: https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#IDToken
      properties:
        iss:
          type: string
          description: issuer
          example: iss
        sub:
          type: string
          description: subject
          example: sub
        aud:
          type: string
          description: audience
          example: aud
        exp:
          type: integer
          description: expires_at
          example: 1687360973
        iat:
          type: integer
          description: issued_at
          example: 1687360973
        auth_time:
          type: integer
          description: auth_time
          example: 1687360973
        nonce:
          type: string
          description: nonce
          example: nonce
      required:
        - iss
        - sub
        - aud
        - exp
        - iat
        - auth_time
        - nonce
